//Calling Minim library
import ddf.minim.*;
public class Mic {
  
  //Declares all classes from Minim
  Minim minim;
  AudioOutput out;
  AudioInput in;
  
  //Enabled monitoring to create a "wind" sound which is generated by the user
  public Mic() {
    
    minim = new Minim(this);
    in = minim.getLineIn(); 
    
  }

//Creates a visual for how much is input is being taken in from the mic. Bar will turn red once it reaches .5. 
  void paint() {
    
    fill(255);
    if (in.left.level()>=.5) {
      fill(255, 0, 0);
      
    }
    
    rect(0, 805, in.left.level()*width-200, 40);
    rect(0, 805, in.right.level()*width-200, 40);
    
  }
}