//Declared library and public variable used to alter the cloud and background colour.
import lmu.*;
public int cd;
class buildingLight {

  //Declared variables
  float multi;
  int left;
  int r = 255;
  int g = 250;
  int b = 85;

  buildingLight() {

    // Sensor values brought in
    int[] lmu_start = LmuTracker.getLMUArray();
    left  = lmu_start[0];
    multi = 255.0 / (left);
  }

  void paint() {
    // Current sensor values
    int[] vals = LmuTracker.getLMUArray();
    int li = (int)(vals[0] * multi)%254;

    // Left Sensor

    if (li == 1) {
      li=255;
    }

    //If the left sensor detects a certain amount, the cd variable will be equal to a set amount, as the light sensor can be very jumpy.
    if (li<=255&&li>=200) {
      cd=0;
    } else if (li<=199&&li>=150) {
      cd=50;
    } else if (li<=149&&li>=100) {
      cd=120;
    } else if (li<=99&&li>=50) {
      cd=150;
    } else if (li<=49&&li>=00) {
      cd=170;
    }

    //Lighting for the CN Tower. This is generated by the time of day
    fill((hour()*10)-li, (minute()*4)-li, (second()*4)-li);
    rect (635, 405, 10, 250);

    //Lighting for the buildings, set to a certain colour and alter depending on the amount of light received by the sensor.
    fill(250-li, 244-li, 162-li);

    //Creation and placement of all building lights
    rect (0, 540, 140, 250);
    rect (140, 620, 105, 180);
    rect (250, 510, 130, 270);
    rect (380, 570, 117, 230);
    rect (500, 650, 800, 150);
    rect (790, 565, 500, 150);
    rect (940, 492, 150, 80);
    rect (1050, 539, 150, 80);

    //Tint of the tower and placement of the images.
    //The tower has two different pieces to it. One is layed under the buildings so the opac part is seen as the same colour, but one the light sensor
    //Detects less light, then it fades away, while the other tower gets tinted depending on the time of day.
    noStroke();
    tint(hour()*10, minute()*4, second()*4);
    image(tower, 0, 0);
    tint(255, 0+li);
    image(tower, 0, 0);

    noTint();
    image(buildings, 0, 0);
  }
}